name: Action 3
on:
  workflow_run:
    workflows: ["Action 1", "Action 2"]
    types:
      - completed

jobs:
  retrieve-artifacts:
    name: Retrieve Artifacts
    runs-on: ubuntu-latest
    outputs:
      action1_run_number: ${{ steps.download_action1.outputs.run_number }}
      action2_run_number: ${{ steps.download_action2.outputs.run_number }}
    steps:
      - name: Download Action 1 Artifact
        id: download_action1
        run: |
          response=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts")
          artifact_url=$(echo "$response" | jq -r '.artifacts[] | select(.name == "action1-run-number") | .archive_download_url')
          curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L -o action1-artifact.zip "$artifact_url"
          mkdir -p action1-run-number
          unzip -o action1-artifact.zip -d action1-run-number
          run_number=$(cat action1-run-number/run_number.txt)
          echo "::set-output name=run_number::$run_number"

      - name: Download Action 2 Artifact
        id: download_action2
        run: |
          response=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts")
          artifact_url=$(echo "$response" | jq -r '.artifacts[] | select(.name == "action2-run-number") | .archive_download_url')
          curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L -o action2-artifact.zip "$artifact_url"
          mkdir -p action2-run-number
          unzip -o action2-artifact.zip -d action2-run-number
          run_number=$(cat action2-run-number/run_number.txt)
          echo "::set-output name=run_number::$run_number"

  display-run-numbers:
    name: Display Run Numbers
    runs-on: ubuntu-latest
    needs: [retrieve-artifacts]
    steps:
      - name: Retrieve Action 1 Run Number
        run: echo "The run number of Action 1 is ${{ needs.retrieve-artifacts.outputs.action1_run_number }}"

      - name: Retrieve Action 2 Run Number
        run: echo "The run number of Action 2 is ${{ needs.retrieve-artifacts.outputs.action2_run_number }}"
