name: Action 3
on:
  workflow_run:
    workflows: ["Action 1", "Action 2"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Run Numbers
        id: retrieve
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            run_number_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
            artifacts=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$run_number_url" | jq -r '.artifacts[].name')
            for artifact in $artifacts; do
              echo "::set-output name=${artifact}_run_number::$(curl -s -H 'Accept: application/vnd.github.v3+json' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$run_number_url" | jq -r --arg artifact "$artifact" '.artifacts[] | select(.name == $artifact) | .run_number')"
            done
          fi

      - name: Output Run Numbers
        run: |
          echo "The run number of Action 1 is ${{ steps.retrieve.outputs.action1-run-number }}"
          echo "The run number of Action 2 is ${{ steps.retrieve.outputs.action2-run-number }}"
