name: Action 2
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output Run Number
        run: |
          echo "The run number of Action 2 is ${{ github.run_number }}"
          echo "${{ github.run_number }}" > run-number.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: action2-run-number
          path: run-number.txt
