name: Action 3
on:
  workflow_run:
    workflows: ["Action 1", "Action 2"]
    types:
      - completed

jobs:
  dummy-job:
    name: Dummy Job
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy job"

  retrieve-action1-run-number:
    name: Retrieve Action 1 Run Number
    runs-on: ubuntu-latest
    needs: [dummy-job]
    steps:
      - name: Download Action 1 Artifact
        uses: actions/download-artifact@v2
        with:
          name: action1-run-number
          path: action1-artifact

      - name: Output Action 1 Run Number
        run: |
          action1_run_number=$(cat action1-artifact/run-number.txt)
          echo "::set-output name=action1_run_number::$action1_run_number"

  retrieve-action2-run-number:
    name: Retrieve Action 2 Run Number
    runs-on: ubuntu-latest
    needs: [dummy-job]
    steps:
      - name: Download Action 2 Artifact
        uses: actions/download-artifact@v2
        with:
          name: action2-run-number
          path: action2-artifact

      - name: Output Action 2 Run Number
        run: |
          action2_run_number=$(cat action2-artifact/run-number.txt)
          echo "::set-output name=action2_run_number::$action2_run_number"

  display-run-numbers:
    name: Display Run Numbers
    runs-on: ubuntu-latest
    needs: [retrieve-action1-run-number, retrieve-action2-run-number]
    steps:
      - name: Retrieve Action 1 Run Number
        run: echo "The run number of Action 1 is ${{ needs.retrieve-action1-run-number.outputs.action1_run_number }}"

      - name: Retrieve Action 2 Run Number
        run: echo "The run number of Action 2 is ${{ needs.retrieve-action2-run-number.outputs.action2_run_number }}"
