name: Action 3
on:
  workflow_run:
    workflows: ["Action 1", "Action 2"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Action 1 Artifact
        uses: actions/download-artifact@v2
        with:
          name: action1-run-number
          path: action1-artifact

      - name: Download Action 2 Artifact
        uses: actions/download-artifact@v2
        with:
          name: action2-run-number
          path: action2-artifact

      - name: Output Run Numbers
        run: |
          action1_run_number=$(cat action1-artifact/run_number)
          action2_run_number=$(cat action2-artifact/run_number)

          echo "The run number of Action 1 is $action1_run_number"
          echo "The run number of Action 2 is $action2_run_number"
